/// <reference types="Cypress" />
describe('Opciones de Click', () => {
    beforeEach(() => {
        cy.viewport('macbook-11')
        cy.orangehrm()
    })

    it('Click sencillo', () => {
        cy.title().should('eq', 'OrangeHRM')
        cy.wait(3500)
        cy.get('#txtUsername').should('be.visible').type('Admin')
        cy.wait(3500)
        cy.get('#txtPassword').should('be.visible').type('admin123')
        cy.wait(3500)
        cy.get('#btnLogin').should('be.visible').click()
        cy.wait(3500)
        cy.get('#menu_admin_viewAdminModule > b').should('be.visible').click()
        cy.wait(3500)
        cy.get('#menu_admin_Job').should('not.be.visible').should('be.hidden').click()
        cy.wait(3500)
    })
    it('Click force true', () => {
        cy.title().should('eq', 'OrangeHRM')
        cy.wait(3500)
        cy.get('#txtUsername').should('be.visible').type('Admin')
        cy.wait(3500)
        cy.get('#txtPassword').should('be.visible').type('admin123')
        cy.wait(3500)
        cy.get('#btnLogin').should('be.visible').click()
        cy.wait(3500)
        cy.get('#menu_admin_viewAdminModule > b').should('be.visible').click()
        cy.wait(3500)
        cy.get('#menu_admin_Job').should('not.be.visible').should('be.hidden').click({ force: true })
        cy.wait(3500)
    })
    it.only('Click por coordenada (x, y)', () => {
        cy.title().should('eq', 'OrangeHRM')
        cy.wait(3500)
        cy.get('#txtUsername').should('be.visible').type('Admin')
        cy.wait(3500)
        cy.get('#txtPassword').should('be.visible').type('admin123')
        cy.wait(3500)
        cy.get('#btnLogin').should('be.visible').click()
        cy.wait(3500)
        cy.get('h1').should('be.visible').click(50,3)
        cy.get('h1').should('be.visible').click(70,-10, { force: true })
    })
})