/// <reference types="Cypress" />
describe('Primer reto del curso', () => {
    beforeEach(() => {
        cy.viewport('macbook-11')
        cy.demoqaWebTables()
        cy.title().should('eq', 'ToolsQA')
    })

    it('Realizanción del primer reto', () => {
        cy.wait(3500)
        cy.get('#searchBox').should('be.visible').should('be.enabled').type('Cierra')
    })
    it('Realizanción del primer reto, limpiando el search', () => {
        // cy.title().should('eq', 'ToolsQA')
        cy.wait(3500)
        cy.get('#searchBox').should('be.visible').should('be.enabled').type('Cierra')
        cy.wait(3500)
        cy.get('#searchBox').should('be.visible').should('be.enabled').clear()
        cy.wait(3500)
    })
    it('Dar click en el boton add y abriendo el formulario', () => {
        cy.wait(3500)
        cy.get('#addNewRecordButton').should('be.visible').should('be.enabled').click()
        cy.wait(3500)
    })
    it('Completando el formulario', () => {
        cy.wait(3500)
        cy.get('#addNewRecordButton').should('be.visible').should('be.enabled').click()
        cy.wait(3500)
        cy.get('#firstName').should('be.empty').should('be.enabled').type('Guy').tab().type('Sánchez').tab().type('guy.sanchez97@hotmail.com')
        cy.wait(3500)
        cy.get('#age').should('be.empty').should('be.enabled').type('25')
        cy.wait(3500)
        cy.get('#salary').should('be.empty').should('be.enabled').type('25000')
        cy.wait(3500)
        cy.get('#department').should('be.empty').should('be.enabled').type('Development')
        cy.wait(3500)
        cy.get('#submit').should('be.visible').should('be.enabled').click()
        cy.wait(3500)
    })
    it('Buscar al nuevo registro', () => {
        cy.wait(3500)
        cy.get('#addNewRecordButton').should('be.visible').should('be.enabled').click()
        cy.wait(3500)
        cy.get('#firstName').should('be.empty').should('be.enabled').type('Guy').tab().type('Sánchez').tab().type('guy.sanchez97@hotmail.com')
        cy.wait(3500)
        cy.get('#age').should('be.empty').should('be.enabled').type('25')
        cy.wait(3500)
        cy.get('#salary').should('be.empty').should('be.enabled').type('25000')
        cy.wait(3500)
        cy.get('#department').should('be.empty').should('be.enabled').type('Development')
        cy.wait(3500)
        cy.get('#submit').should('be.visible').should('be.enabled').click()
        cy.wait(3500)
        cy.get('#searchBox').should('be.visible').should('be.enabled').type('Guy')
        cy.wait(3500)
    })
    it('Editando un registro', () => {
        cy.wait(3500)
        cy.get('#edit-record-3').should('be.visible').should('not.be.enabled').click()
        cy.wait(3500)
        cy.get('#age').should('be.enabled').should('have.value', '29').clear().type('31')
        cy.wait(3500)
        cy.get('#salary').should('be.enabled').should('have.value', '2000').clear().type('25000')
        cy.wait(3500)
        cy.get('#submit').should('be.visible').should('be.enabled').click()
        cy.wait(3500)
    })
    it('Elimnar un registro', () => {
        cy.wait(3500)
        cy.get('#delete-record-2').should('be.visible').should('not.be.enabled').click()
        cy.wait(3500)
    })
})